
spring:
  mvc:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2

  server:
    error:
      whitelabel:
        enabled: false
